#!/usr/bin/env bash
ARCHIVE="https://odooku.s3.amazonaws.com/runtimes/python-2.7.12.tar.gz"

if [ ! -f ".heroku/odoo/bin/python" ]; then
  puts-step "Bootstrapping Python 2.7.12"
  mkdir -p .heroku/odoo
  curl $ARCHIVE -s | tar zxv -C .heroku/odoo &> /dev/null
fi
