#!/usr/bin/env bash

# Parse heroku DATABASE_URL
if [[ $DATABASE_URL =~ ^postgres.* ]]; then
    ODOOKU_DB_USER:=$(echo $DATABASE_URL | sed -e 's/^postgres:\/\/\(.*\):.*@.*:.*\/.*$/\1/')
    ODOOKU_DB_PASSWORD:=$(echo $DATABASE_URL | sed -e 's/^postgres:\/\/.*:\(.*\)@.*:.*\/.*$/\1/')
    ODOOKU_DB_HOST:=$(echo $DATABASE_URL | sed -e 's/^postgres:\/\/.*:.*@\(.*\):.*\/.*$/\1/')
    ODOOKU_DB_PORT:=$(echo $DATABASE_URL | sed -e 's/^postgres:\/\/.*:.*@.*:\(.*\)\/.*$/\1/')
    ODOOKU_DB_NAME:=$(echo $DATABASE_URL | sed -e 's/^postgres:\/\/.*:.*@.*:.*\/\(.*\)$/\1/')
fi

ODOOKU_PORT=$0
ODOOKU_ADDONS:=""
ODOOKU_DATA_DIR:="/tmp"
ODOOKU_ADMIN_PASSWORD:=""
ODOOKU_DEBUG:="0"
ODOOKU_AWS_ACCESS_KEY_ID:=""
ODOOKU_AWS_ACCESS_KEY_SECRET:=""
ODOOKU_S3_BUCKET:=""


options="--xmlrpc-port $ODOOKU_PORT --addons-path $ODOOKU_ADDONS --data-dir $ODOOKU_DATA_DIR --db_host $ODOOKU_DB_HOST --db_port $ODOOKU_DB_PORT -d $ODOOKU_DB_NAME -r $ODOOKU_DB_USER -w $ODOOKU_DB_PASSWORD"
odoo.py $options
